apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: real-time-platform
data:
  KAFKA_BOOTSTRAP_SERVERS: "event-cluster-kafka-bootstrap.kafka:9092"
  KAFKA_TOPIC: "user-events"
  REDIS_HOST: "redis-master.redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: ""
  POSTGRES_DB: "eventdb"
  POSTGRES_PORT: "5432" 