apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: real-time-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: real-time-platform/postgres
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: real-time-platform/postgres
      property: password