# Secrets is best managed via AWS Secrets Manager / External Secrets Operator - this file is a placeholder for development purposes
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: real-time-platform
type: Opaque
data: {}
